name: Deploy Finnhub Ingestor

on:
  push:
    branches:
      - main
    # THIS IS THE MAGIC: Only trigger if files in this specific folder change
    paths:
      - 'src/finnhub/**'

env:
  PROJECT_ID: 'mike-personal-portfolio'
  REGION: 'us-central1'
  REPO_NAME: 'financial-trackers' # Your Artifact Registry repo
  SERVICE_NAME: 'finnhub-ingestor'

jobs:
  ci-checks:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      
      # 1 Secret Scanning
      - name: Gitleaks Secret Scanner
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # 2 Code Formatting
      - name: Check Formatting with Black
        uses: psf/black@stable
        with:
          src: "./src/finnhub"
          opions: '--check'
      
      # 3 Static Application Security Testing (Banit)
      - name: Security Scan with bandit
        run: |
          pip install bandit
          bandit -r ./src/finnhub -lll


  build-and-deploy:
    runs-on: ubuntu-latest
    needs: ci-checks
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      # Step 1: Pull down your repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Docker Tag
        run: echo "DOCKER_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV
         
      # Step 2: Authenticate securely to GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/166016129616/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider-v2'
          service_account: 'github-actions-sa@mike-personal-portfolio.iam.gserviceaccount.com'

      # Step 3: Configure Docker to talk to your GCP Artifact Registry
      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Step 4: Build the container and push it to Artifact Registry
      - name: Build and Push Container
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t ${{ env.DOCKER_TAG }} src/finnhub
          
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Push Container
        run: docker push ${{ env.DOCKER_TAG }}

      # Step 5: Tell Cloud Run to spin up the new image
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.DOCKER_TAG }}

          env_vars: |
            PROJECT_ID=mike-personal-portfolio
            
          # 2. Secure API Keys from Secret Manager
          # Format: ENV_VAR_NAME=secret-name-in-gcp:version
          secrets: |
            FINNHUB_API_KEY=finnhub_api_key:latest